//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techie
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        public int OrderId { get; set; }
        public string OrderBuyerName { get; set; }
        public string OrderSellerName { get; set; }
        public string OrderDate { get; set; }
        public int OrderQty { get; set; }
        public int OrderPriceTotal { get; set; }
    }
}
