//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techie
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTable
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreEmail { get; set; }
        public string StorePassword { get; set; }
        public string StoreProfilePicture { get; set; }
        public string StorePhoneNumber { get; set; }
        public string StoreAddress { get; set; }
        public string StoreGrade { get; set; }
    }
}
